### ISSUE TITLE
Cannot install requirements

### ISSUE THREAD

**Issue by marmhm** [liu-yushan/PoLo#1]
Hi, we are trying to use PoLo, we tried to install the requirements from the `requirements.txt` file but it does not seems to be in a valid format

We tried:

```
pip install -r requirements.txt
```

Getting error: 

> ERROR: Invalid requirement: '_libgcc_mutex=0.1=conda_forge' (from line 4 of .\requirements.txt)
Hint: = is not a valid operator. Did you mean == ?

And:

```
conda install --file requirements.txt
```

Getting error:

```
PackagesNotFoundError: The following packages are not available from current channels:
  - rsa==4.7.2=pyh44b312d_0
  - markdown==3.3.4=pyhd8ed1ab_0
  - gast==0.4.0=pyh9f0ad1d_0
```

What can be used to install the requirements?

**Comment by liu-yushan** [comment]
Hi, I created the requirements file automatically with conda so the syntax is probably different from `pip`. I'm not sure which channels should be added. What you can try is to run `run.sh` and install any library (take the version from `requirements.txt`) that is shown to be missing (ImportError).  There should only be a few libraries that need to be installed. This usually works for me.

**Comment by omerdotdev** [comment]
@marmhm @liu-yushan 
Here I added a [colab](https://colab.research.google.com/drive/1jcMcD8eBUj6qzyXtvyGHo4P2Rzo4RDze?usp=sharing) for this initial step of setting up the environment. also [here](https://github.com/omerdotdev/PoLo/blob/main/PoLo-env-setup.ipynb) (214a067)

After setting up in colab:

`!source run.sh configs/{cofig_file}.sh`

Hope, it helps folks from the future.
Good Luck!

**Comment by ddomingof** [comment]
Can someone post any requirements that work? 
I wasn't able to get it running after investing a couple of hours.

**Comment by laurendelong21** [comment]
+1

**Comment by liu-yushan** [comment]
Hi, I updated the ```requirements.txt``` file. Please try out the new file by using, e.g., ```pip install -r requirements.txt```.

**Comment by laurendelong21** [comment]
It works for me, thanks so much!
