### ISSUE TITLE
torch version

### ISSUE THREAD

**Issue by chrislouis0106** [liu-yushan/PoLo#2]
Hi, there,
Is there a torch version of the code?
Regards

**Comment by liu-yushan** [comment]
Hi, there is no torch version of the code. However, there exists a torch version of MINERVA (on which our code is based): https://github.com/ty4b112/pytorch_MINERVA

**Comment by chrislouis0106** [comment]
Thank you very much. The rule processor offered is very helpful to me, and I would like to ask if there are other rule learners besides AnyBURL?

**Comment by liu-yushan** [comment]
Here is a list of rule-based methods for KGs along with the papers and code (if available): 
https://github.com/xinguoxia/KGE#rules

**Comment by chrislouis0106** [comment]
Yeah, I know that, thank your response.
